using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using TaskManagementApi.Core.DTOs.DTO_Tasks;
using TaskManagementApi.Core.Entities;

namespace TaskManagementApi.Core.Mapping_Profiles
{
    public class TaskMappingProfile : Profile
    {
        public TaskMappingProfile()
        {
            CreateMap<DTO_TaskPost, TaskItem>()
                .ForMember(dest => dest.Id, opt => opt.Ignore()) // Id is generated by DB
                .ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src.AssignedToUserId != null ? src.AssignedToUserId : (string)null))
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore()) // CreatedAt set in service
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore()) // UpdatedAt set in service
                .ForMember(dest => dest.IsCompleted, opt => opt.MapFrom(src => false)) // Default for new tasks
                .ForMember(dest => dest.User, opt => opt.Ignore()) // User navigation property ignored
                .ForMember(dest => dest.AssignedByUser, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.MapFrom(src => false)) // Default for new tasks
                .ForMember(dest => dest.DeletedAt, opt => opt.Ignore()) // Not set on creation
                .ForMember(dest => dest.IsNotified, opt => opt.MapFrom(src => false))
                .ForMember(dest => dest.TaskItemTags, opt => opt.Ignore());


            CreateMap<TaskItem, DTO_TaskGet>()
                .ForMember(dest => dest.UserName, opt => opt.MapFrom(src => src.User.UserName))
                .ForMember(dest => dest.AssignedToUserName, opt => opt.MapFrom(src => src.User.UserName))
                .ForMember(dest => dest.AssignedByUserName, opt => opt.MapFrom(src => src.AssignedByUser != null ? src.AssignedByUser.UserName : null))
                .ForMember(dest => dest.Tags, opt => opt.MapFrom(src => src.TaskItemTags.Select(tit => tit.Tag.Name).ToList()));

            CreateMap<DTO_TaskPut, TaskItem>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)) // Ensure Id is mapped if present in DTO
                .ForMember(dest => dest.UserId, opt => opt.Ignore()) // UserId should not be updated via PUT
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore()) // CreatedAt should not be updated via PUT
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore()) // UpdatedAt set in service
                .ForMember(dest => dest.User, opt => opt.Ignore())
                .ForMember(dest => dest.AssignedByUser, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore()) // IsDeleted not updated via PUT
                .ForMember(dest => dest.DeletedAt, opt => opt.Ignore()) // DeletedAt not updated via PUT
                .ForMember(dest => dest.IsNotified, opt => opt.Ignore())
                .ForMember(dest => dest.TaskItemTags, opt => opt.Ignore());
        }

    }
}
